name: calisfun
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  hexcolor: ^3.0.1
  google_fonts: ^6.3.0
  go_router: ^16.1.0
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.0
  image_picker: ^1.1.2
  google_mlkit_digital_ink_recognition: ^0.14.1
  speech_to_text: ^7.3.0
  google_nav_bar: ^5.0.7
  equatable: ^2.0.7
  dio: ^5.9.0
  uuid: ^4.4.2
  http: ^1.1.0
  freezed: ^3.1.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  freezed_annotation: ^3.1.0
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  path: ^1.9.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/calisfun_logo.png"

flutter:
  uses-material-design: true

  assets:
     - assets/images/
     - assets/icons/
     - .env.development
     - .env.production