name: Release APK (debug, no secrets)

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'workflow_dispatch' && 'main' || github.ref }}

      - name: Setup Flutter (stable, pinned)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.29.0'
          cache: true

      - name: Doctor & versions
        run: |
          which flutter && flutter --version
          which dart && dart --version
          echo "----- pubspec environment -----"
          awk '/^environment:/{p=1;print;next} p && NF==0{p=0} p' pubspec.yaml

      - name: Flutter clean
        run: flutter clean

      - name: Flutter pub get
        run: flutter pub get

      - name: Static analysis
        run: flutter analyze

      - name: Run tests (with coverage)
        run: flutter test --coverage

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
