name: Release APK (debug, no secrets)

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter (latest stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Static analysis
        run: flutter analyze

      - name: Run tests (with coverage)
        run: flutter test --coverage

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
